b6
Zavadovics/group-11-github pull request #1
Opened 2021-06-07 15:55 UTC by vocseikati

2021-06-07 15:57 UTC, vocseikati commented
blabla

2021-06-08 08:10 UTC, ntexs8 requested changes

2021-06-08 08:10 UTC, ntexs8 commented on src/TomiFirstJavaFile.java
>      }
próba review:
Jól néz ki tetszik. A konfliktusokat még fel kell oldanod. Szerintem meg tarthatod a te változtatásaidat.

2021-06-08 08:10 UTC, ntexs8 commented on src/TomiFirstJavaFile.java
> +        System.out.println("'Greetings for the " + param);
Felkiáltójel maradhat a végén.

2021-06-08 08:22 UTC, vocseikati commented on src/TomiFirstJavaFile.java
> +        System.out.println("'Greetings for the " + param);
Rendben, a felkiáltójelet berakom még.

2021-06-08 08:39 UTC, ntexs8 approved these changes
Elfogadom és apprúvolom.

2021-06-08 08:52 UTC, merged